import Image from "next/image";
import CategoryTabs from "@/components/CategoryTabs";
import MenuProductList from "@/components/MenuProductList";
import DemoScrollFix from "@/components/DemoScrollFix";

const PRIMARY = "#f97316";
const LOGO  = "/demo/logo.png";
const COVER = "/demo/cafe-cover.png";

const PRODUCTS = [
  // ── KAHVELER ──────────────────────────────────────────────────────────────
  { id: "k1",  name: "Türk Kahvesi",       name_en: "Turkish Coffee",      price: 38,  category: "Kahveler",          description: "Geleneksel tarif, yoğun köpüklü",            description_en: "Traditional, rich foam",               image_url: "/demo/turk-kahvesi.png",  tags: ["Popüler"],        ingredients: ["coffee","water"],                                           in_stock: true,  model_url: null },
  { id: "k2",  name: "Sütlü Latte",        name_en: "Latte",               price: 58,  category: "Kahveler",          description: "Çift espresso, buharda süt",                 description_en: "Double espresso, steamed milk",        image_url: "/demo/latte.png",         tags: ["Popüler"],        ingredients: ["espresso","milk"],                                          in_stock: true,  model_url: null },
  { id: "k3",  name: "Cappuccino",         name_en: "Cappuccino",          price: 55,  category: "Kahveler",          description: "Yoğun espresso, kadifemsi köpük",            description_en: "Intense espresso, velvety foam",       image_url: "/demo/Capuccino.png",     tags: [],                 ingredients: ["espresso","milk"],                                          in_stock: true,  model_url: null },
  { id: "k4",  name: "Americano",          name_en: "Americano",           price: 48,  category: "Kahveler",          description: "Sıcak su ile uzatılmış espresso",            description_en: "Espresso with hot water",              image_url: "/demo/americano.png",     tags: [],                 ingredients: ["espresso","water"],                                         in_stock: true,  model_url: null },
  { id: "k5",  name: "Flat White",         name_en: "Flat White",          price: 62,  category: "Kahveler",          description: "Ristretto üzeri kadifemsi mikroköpük",       description_en: "Ristretto with velvety microfoam",     image_url: "/demo/flat-white.jpeg",   tags: ["Öne Çıkan"],      ingredients: ["espresso","milk"],                                          in_stock: true,  model_url: null },
  { id: "k6",  name: "Cortado",            name_en: "Cortado",             price: 52,  category: "Kahveler",          description: "Espresso ve az sütün mükemmel dengesi",     description_en: "Perfect balance of espresso & milk",   image_url: "/demo/cortado.jpeg",      tags: ["Yeni"],           ingredients: ["espresso","milk"],                                          in_stock: true,  model_url: null },
  { id: "k7",  name: "Filtre Kahve",       name_en: "Filter Coffee",       price: 45,  category: "Kahveler",          description: "Günlük taze öğütülmüş, yavaş demleme",      description_en: "Daily fresh ground, slow brew",        image_url: "/demo/filtre-kahve.jpeg", tags: [],                 ingredients: ["coffee","water"],                                           in_stock: true,  model_url: null },
  { id: "k8",  name: "Karamel Macchiato",  name_en: "Caramel Macchiato",   price: 68,  category: "Kahveler",          description: "Vanilyalı süt, espresso, karamel sos",      description_en: "Vanilla milk, espresso, caramel",      image_url: "/demo/karamel-macchiato.jpeg", tags: ["Popüler"],   ingredients: ["espresso","milk","vanilla","caramel"],                      in_stock: true,  model_url: null },
  { id: "k9",  name: "Mocha",              name_en: "Mocha",               price: 65,  category: "Kahveler",          description: "Espresso, çikolata sosu, süt köpüğü",       description_en: "Espresso, chocolate sauce, foam",      image_url: "/demo/mocha.jpeg",        tags: ["Şefin Seçimi"],   ingredients: ["espresso","milk","chocolate"],                              in_stock: true,  model_url: null },
  { id: "k10", name: "Espresso",           name_en: "Espresso",            price: 35,  category: "Kahveler",          description: "Saf, yoğun tek shot espresso",              description_en: "Pure, intense single shot",            image_url: "/demo/espresso.jpeg",     tags: [],                 ingredients: ["espresso"],                                                 in_stock: true,  model_url: null },
  { id: "k11", name: "Double Espresso",    name_en: "Double Espresso",     price: 45,  category: "Kahveler",          description: "Çift shot, güçlü başlangıç",                description_en: "Double shot, strong start",            image_url: "/demo/double-espresso.jpeg", tags: [],              ingredients: ["espresso"],                                                 in_stock: true,  model_url: null },
  { id: "k12", name: "Fındıklı Latte",     name_en: "Hazelnut Latte",      price: 65,  category: "Kahveler",          description: "Espresso, süt, ev yapımı fındık şurubu",   description_en: "Espresso, milk, house hazelnut syrup", image_url: "/demo/findikli-latte.jpeg", tags: ["Öne Çıkan"],  ingredients: ["espresso","milk","hazelnut"],                               in_stock: true,  model_url: null },

  // ── SICAK İÇECEKLER ────────────────────────────────────────────────────────
  { id: "s1",  name: "Sıcak Çikolata",     name_en: "Hot Chocolate",       price: 55,  category: "Sıcak İçecekler",   description: "Belçika çikolatası, kremşanti",              description_en: "Belgian chocolate, whipped cream",     image_url: "/demo/sicak-cikolata.jpeg", tags: ["Popüler"],      ingredients: ["chocolate","milk","cream","sugar"],                         in_stock: true,  model_url: null },
  { id: "s2",  name: "Beyaz Çikolata",     name_en: "White Hot Choc",      price: 58,  category: "Sıcak İçecekler",   description: "Beyaz çikolata, süt köpüğü, vanilya",       description_en: "White chocolate, foam, vanilla",       image_url: "/demo/beyaz-cikolata.jpeg", tags: ["Yeni"],          ingredients: ["chocolate","milk","vanilla","cream"],                       in_stock: true,  model_url: null },
  { id: "s3",  name: "Chai Latte",         name_en: "Chai Latte",          price: 52,  category: "Sıcak İçecekler",   description: "Baharatlı çay, köpüklü süt, tarçın",        description_en: "Spiced tea, frothy milk, cinnamon",    image_url: "/demo/chai-latte.jpeg",   tags: ["Öne Çıkan"],      ingredients: ["tea","milk","cinnamon","sugar"],                            in_stock: true,  model_url: null },
  { id: "s4",  name: "Matcha Latte",       name_en: "Matcha Latte",        price: 65,  category: "Sıcak İçecekler",   description: "Seremoni matcha, sıcak köpüklü süt",        description_en: "Ceremonial matcha, hot frothy milk",   image_url: "/demo/matcha-latte.jpeg", tags: ["Popüler"],        ingredients: ["tea","milk","sugar"],                                       in_stock: true,  model_url: null },
  { id: "s5",  name: "Türk Çayı",          name_en: "Turkish Tea",         price: 18,  category: "Sıcak İçecekler",   description: "Çift demlik, ince belli bardak",            description_en: "Double brewed, traditional glass",     image_url: "/demo/turk-cayi.jpeg",    tags: [],                 ingredients: ["tea","water"],                                              in_stock: true,  model_url: null },
  { id: "s6",  name: "Bitki Çayı",         name_en: "Herbal Tea",          price: 32,  category: "Sıcak İçecekler",   description: "Ihlamur, nane-limon veya papatya",          description_en: "Linden, mint-lemon or chamomile",      image_url: null,                      tags: [],                 ingredients: ["tea","mint","lemon"],                                       in_stock: true,  model_url: null },
  { id: "s7",  name: "Salep",              name_en: "Salep",               price: 42,  category: "Sıcak İçecekler",   description: "Geleneksel Türk içeceği, tarçınlı",         description_en: "Traditional Turkish drink, cinnamon",  image_url: "/demo/salep.jpeg",        tags: ["Sınırlı"],        ingredients: ["milk","starch","sugar","cinnamon"],                         in_stock: true,  model_url: null },

  // ── SOĞUK İÇECEKLER ────────────────────────────────────────────────────────
  { id: "c1",  name: "Ice Latte",          name_en: "Iced Latte",          price: 68,  category: "Soğuk İçecekler",   description: "Buzlu espresso, soğuk süt",                 description_en: "Iced espresso, cold milk",             image_url: "/demo/ice-latte.png",     tags: ["Popüler"],        ingredients: ["espresso","milk","ice"],                                    in_stock: true,  model_url: null },
  { id: "c2",  name: "Cold Brew",          name_en: "Cold Brew",           price: 72,  category: "Soğuk İçecekler",   description: "18 saat soğuk demleme, yumuşak tat",        description_en: "18h cold steep, smooth taste",         image_url: "/demo/cold-brew.jpeg",    tags: ["Öne Çıkan"],      ingredients: ["coffee","water","ice"],                                     in_stock: true,  model_url: null },
  { id: "c3",  name: "Limonata",           name_en: "Lemonade",            price: 48,  category: "Soğuk İçecekler",   description: "Taze sıkılmış limon, nane, buz",            description_en: "Fresh lemon, mint, ice",               image_url: "/demo/limonata.png",      tags: [],                 ingredients: ["lemon","water","sugar","mint","ice"],                       in_stock: true,  model_url: null },
  { id: "c4",  name: "Mango Smoothie",     name_en: "Mango Smoothie",      price: 72,  category: "Soğuk İçecekler",   description: "Taze mango, yoğurt, bal",                   description_en: "Fresh mango, yogurt, honey",           image_url: "/demo/mango-smootihe.png",tags: ["Yeni"],           ingredients: ["mango","yogurt","honey","ice"],                             in_stock: true,  model_url: null },
  { id: "c5",  name: "Berry Smoothie",     name_en: "Berry Smoothie",      price: 70,  category: "Soğuk İçecekler",   description: "Çilek, yaban mersini, muz, yoğurt",         description_en: "Strawberry, blueberry, banana",        image_url: "/demo/berry-smoothie.jpeg", tags: ["Popüler"],      ingredients: ["strawberry","blueberry","banana","yogurt","ice"],           in_stock: true,  model_url: null },
  { id: "c6",  name: "Soğuk Matcha",       name_en: "Iced Matcha",         price: 70,  category: "Soğuk İçecekler",   description: "Seremoni matcha, soğuk süt, buzlu",         description_en: "Ceremonial matcha, cold milk",         image_url: "/demo/soguk-matcha.jpeg", tags: ["Şefin Seçimi"],   ingredients: ["tea","milk","sugar","ice"],                                  in_stock: true,  model_url: null },
  { id: "c7",  name: "Portakal Suyu",      name_en: "Orange Juice",        price: 45,  category: "Soğuk İçecekler",   description: "Taze sıkılmış, şekersiz",                   description_en: "Fresh squeezed, no sugar",             image_url: "/demo/portakal-suyu.jpeg",tags: [],                 ingredients: ["orange","ice"],                                             in_stock: true,  model_url: null },
  { id: "c8",  name: "Buzlu Çikolata",     name_en: "Iced Chocolate",      price: 65,  category: "Soğuk İçecekler",   description: "Soğuk süt, Belçika çikolatası, buz",        description_en: "Cold milk, Belgian chocolate, ice",    image_url: "/demo/buzlu-cikolata.jpeg",tags: [],                ingredients: ["chocolate","milk","ice","sugar"],                           in_stock: true,  model_url: null },

  // ── KAHVALTI ───────────────────────────────────────────────────────────────
  { id: "b1",  name: "Serpme Kahvaltı",    name_en: "Turkish Breakfast",   price: 220, category: "Kahvaltı",          description: "Peynir, zeytin, domates, salatalık, yumurta, reçel, bal, tereyağı", description_en: "Cheese, olives, tomatoes, eggs, jam, honey", image_url: "/demo/kahvalti-serpme.png",            tags: ["Popüler","Şefin Seçimi"], ingredients: ["egg","cheese","tomato","cucumber","honey","butter","olive oil"],       in_stock: true,  model_url: null },
  { id: "b2",  name: "Menemen",            name_en: "Menemen",             price: 85,  category: "Kahvaltı",          description: "Yumurta, domates, biber, zeytinyağı",       description_en: "Eggs, tomato, peppers, olive oil",     image_url: "/demo/menemen.png",                      tags: ["Popüler"],        ingredients: ["egg","tomato","pepper","oliveoil","salt"],                  in_stock: true,  model_url: null },
  { id: "b3",  name: "Avokadolu Yumurta",  name_en: "Avocado Eggs",        price: 110, category: "Kahvaltı",          description: "Pişmiş yumurta, avokado ezmesi, çeri domates", description_en: "Poached egg, avocado, cherry tomato", image_url: "/demo/avakado-yumurta.png",                      tags: ["Öne Çıkan"],      ingredients: ["egg","oliveoil","tomato","lemon","salt"],                   in_stock: true,  model_url: null },
  { id: "b4",  name: "Sahanda Yumurta",    name_en: "Fried Eggs",          price: 65,  category: "Kahvaltı",          description: "Tereyağında pişirilmiş, pastırmalı",        description_en: "Butter fried with pastrami",           image_url: "/demo/yumurta-pastirmali.png",                      tags: [],                 ingredients: ["egg","butter","pastrami","salt"],                           in_stock: true,  model_url: null },
  { id: "b5",  name: "Granola Bowl",       name_en: "Granola Bowl",        price: 78,  category: "Kahvaltı",          description: "Yulaf, bal, mevsim meyveleri, yoğurt",      description_en: "Oat, honey, seasonal fruit, yogurt",   image_url: "/demo/granola-bowl.png",                      tags: ["Yeni"],           ingredients: ["oat","honey","yogurt","strawberry","banana"],               in_stock: true,  model_url: null },
  { id: "b6",  name: "Pancake",            name_en: "Pancake",             price: 95,  category: "Kahvaltı",          description: "Taze meyve, akçaağaç şurubu, tereyağı",    description_en: "Fresh fruit, maple syrup, butter",     image_url: "/demo/pancake.png",                      tags: ["Popüler"],        ingredients: ["flour","egg","milk","butter","strawberry","banana"],        in_stock: true,  model_url: null },
  { id: "b7",  name: "Poğaça",             name_en: "Turkish Pastry",      price: 35,  category: "Kahvaltı",          description: "Günlük pişirilir, peynirli veya zeytinli", description_en: "Freshly baked, cheese or olive",       image_url: null,                      tags: [],                 ingredients: ["flour","egg","butter","cheese"],                            in_stock: true,  model_url: null },
  { id: "b8",  name: "Acılı Ezme",         name_en: "Spicy Ezme",          price: 45,  category: "Kahvaltı",          description: "Domates, biber, maydanoz, limon",           description_en: "Tomato, pepper, parsley, lemon",       image_url: null,                      tags: ["Yeni"],           ingredients: ["tomato","pepper","lemon","oliveoil","salt"],                in_stock: true,  model_url: null },

  // ── TOSTLAR & SANDVİÇLER ───────────────────────────────────────────────────
  { id: "t1",  name: "Klasik Tost",        name_en: "Classic Toast",       price: 55,  category: "Tostlar & Sandviçler", description: "Kaşar peyniri, domates, çıtır ekmek",   description_en: "Cheddar, tomato, crispy bread",       image_url: "/demo/tost.png",                      tags: [],                 ingredients: ["flour","cheese","tomato","butter"],                         in_stock: true,  model_url: null },
  { id: "t2",  name: "Tavuklu Sandviç",    name_en: "Chicken Sandwich",    price: 95,  category: "Tostlar & Sandviçler", description: "Izgara tavuk, marul, domates, mayonez",  description_en: "Grilled chicken, lettuce, mayo",      image_url: null,                      tags: ["Popüler"],        ingredients: ["chicken","lettuce","tomato","mayo","flour"],                in_stock: true,  model_url: null },
  { id: "t3",  name: "Pastırmalı Tost",    name_en: "Pastrami Toast",      price: 75,  category: "Tostlar & Sandviçler", description: "Pastırma, kaşar, domates, acı sos",     description_en: "Pastrami, cheese, tomato, hot sauce", image_url: null,                      tags: ["Öne Çıkan"],      ingredients: ["pastrami","cheese","tomato","flour","hotsauce"],            in_stock: true,  model_url: null },
  { id: "t4",  name: "Avokado Toast",      name_en: "Avocado Toast",       price: 95,  category: "Tostlar & Sandviçler", description: "Tam tahıllı ekmek, avokado ezmesi, yumurta", description_en: "Whole grain, avocado, egg",       image_url: null,                      tags: ["Yeni","Öne Çıkan"],ingredients: ["flour","egg","oliveoil","lemon","salt"],                    in_stock: true,  model_url: null },
  { id: "t5",  name: "Ton Balıklı",        name_en: "Tuna Sandwich",       price: 85,  category: "Tostlar & Sandviçler", description: "Ton balığı, mısır, marul, mayo",        description_en: "Tuna, corn, lettuce, mayo",           image_url: null,                      tags: [],                 ingredients: ["fish","corn","lettuce","mayo","flour"],                     in_stock: true,  model_url: null },
  { id: "t6",  name: "Ispanaklı Börek",    name_en: "Spinach Börek",       price: 65,  category: "Tostlar & Sandviçler", description: "Çıtır yufka, ıspanak, beyaz peynir",    description_en: "Crispy phyllo, spinach, white cheese", image_url: null,                      tags: ["Şefin Seçimi"],   ingredients: ["flour","cheese","egg","butter","oliveoil"],                 in_stock: true,  model_url: null },
  { id: "t7",  name: "Mantar Tost",        name_en: "Mushroom Toast",      price: 80,  category: "Tostlar & Sandviçler", description: "Sote mantar, kaşar, kekik, sourdough",  description_en: "Sauteed mushroom, cheese, thyme",     image_url: null,                      tags: ["Yeni"],           ingredients: ["mushroom","cheese","flour","butter","oliveoil"],            in_stock: true,  model_url: null },

  // ── ANA YEMEKLER ───────────────────────────────────────────────────────────
  { id: "a1",  name: "Tavuk Izgara",       name_en: "Grilled Chicken",     price: 165, category: "Ana Yemekler",      description: "Marine edilmiş, yanında pilav ve salata",  description_en: "Marinated, with rice and salad",       image_url: null,                      tags: ["Popüler"],        ingredients: ["chicken","rice","tomato","lettuce","oliveoil","salt"],      in_stock: true,  model_url: null },
  { id: "a2",  name: "Dana Burger",        name_en: "Beef Burger",         price: 175, category: "Ana Yemekler",      description: "180gr dana, özel sos, çıtır patates",      description_en: "180g beef, special sauce, fries",      image_url: null,                      tags: ["Öne Çıkan","Popüler"], ingredients: ["beef","flour","cheese","tomato","lettuce","mayo"],     in_stock: true,  model_url: null },
  { id: "a3",  name: "Karides Güveç",      name_en: "Shrimp Casserole",    price: 195, category: "Ana Yemekler",      description: "Taze karides, domates sosu, tereyağı",     description_en: "Fresh shrimp, tomato sauce, butter",   image_url: null,                      tags: ["Şefin Seçimi"],   ingredients: ["shrimp","tomatosauce","butter","garlic","salt"],            in_stock: true,  model_url: null },
  { id: "a4",  name: "Penne Arrabiata",    name_en: "Penne Arrabiata",     price: 145, category: "Ana Yemekler",      description: "Al dente penne, acılı domates sosu, fesleğen", description_en: "Al dente penne, spicy tomato, basil",  image_url: null,                      tags: [],                 ingredients: ["flour","tomatosauce","garlic","hotsauce","basil","oliveoil"], in_stock: true, model_url: null },
  { id: "a5",  name: "Somon Fillet",       name_en: "Salmon Fillet",       price: 210, category: "Ana Yemekler",      description: "Izgara somon, limon sosu, garnitür",        description_en: "Grilled salmon, lemon sauce, garnish", image_url: null,                      tags: ["Öne Çıkan"],      ingredients: ["fish","lemon","oliveoil","salt","butter"],                  in_stock: true,  model_url: null },
  { id: "a6",  name: "Köfte Tabağı",       name_en: "Meatball Plate",      price: 155, category: "Ana Yemekler",      description: "El yapımı köfte, pilav, közlenmiş sebze",  description_en: "Handmade meatball, rice, grilled veg", image_url: null,                      tags: ["Popüler"],        ingredients: ["beef","onion","egg","flour","rice","pepper","salt"],        in_stock: true,  model_url: null },
  { id: "a7",  name: "Vejetaryen Tabak",   name_en: "Veggie Plate",        price: 130, category: "Ana Yemekler",      description: "Izgara sebze, humus, pide",                description_en: "Grilled veggies, hummus, pide",        image_url: null,                      tags: ["Yeni"],           ingredients: ["eggplant","pepper","tomato","corn","oliveoil","flour"],     in_stock: true,  model_url: null },

  // ── TATLILAR ───────────────────────────────────────────────────────────────
  { id: "d1",  name: "Cheesecake",         name_en: "Cheesecake",          price: 85,  category: "Tatlılar",          description: "Ev yapımı, mevsim meyveli",                 description_en: "Homemade, seasonal fruit",             image_url: "/demo/cheescake.png",     tags: ["Popüler"],        ingredients: ["flour","egg","butter","sugar","cheese","cream"],            in_stock: true,  model_url: null },
  { id: "d2",  name: "Waffle",             name_en: "Waffle",              price: 78,  category: "Tatlılar",          description: "Çikolata sosu ve dondurma ile",             description_en: "Chocolate sauce & ice cream",          image_url: "/demo/waffle.png",        tags: ["Popüler"],        ingredients: ["flour","egg","milk","butter","chocolate","icecream"],       in_stock: true,  model_url: null },
  { id: "d3",  name: "Tiramisu",           name_en: "Tiramisu",            price: 88,  category: "Tatlılar",          description: "İtalyan usulü, ev yapımı, espressolu",     description_en: "Italian style, homemade, espresso",    image_url: null,                      tags: ["Şefin Seçimi"],   ingredients: ["cream","espresso","cocoa","egg","sugar"],                   in_stock: true,  model_url: null },
  { id: "d4",  name: "Brownie",            name_en: "Brownie",             price: 68,  category: "Tatlılar",          description: "Bitter çikolatalı, fındıklı, dondurmalı",  description_en: "Dark chocolate, hazelnut, ice cream",  image_url: null,                      tags: ["Öne Çıkan"],      ingredients: ["chocolate","butter","egg","flour","hazelnut","icecream"],   in_stock: true,  model_url: null },
  { id: "d5",  name: "Fındıklı Kurabiye",  name_en: "Hazelnut Cookie",     price: 38,  category: "Tatlılar",          description: "Günlük taze pişirilir, 2 adet",            description_en: "Freshly baked daily, 2 pcs",           image_url: "/demo/cookie.png",        tags: [],                 ingredients: ["flour","sugar","hazelnut","butter","egg"],                  in_stock: true,  model_url: null },
  { id: "d6",  name: "Profiterol",         name_en: "Profiterole",         price: 92,  category: "Tatlılar",          description: "Çikolata sosu, kremalı içi, fıstık",       description_en: "Chocolate sauce, cream filling",       image_url: null,                      tags: ["Popüler"],        ingredients: ["flour","egg","butter","cream","chocolate","peanut"],        in_stock: true,  model_url: null },
  { id: "d7",  name: "Künefe",             name_en: "Künefe",              price: 95,  category: "Tatlılar",          description: "Tel kadayıf, peynir dolgusu, şerbet",      description_en: "Shredded phyllo, cheese, syrup",       image_url: null,                      tags: ["Sınırlı","Şefin Seçimi"], ingredients: ["flour","cheese","butter","sugar"],              in_stock: true,  model_url: null },
  { id: "d8",  name: "Dondurma",           name_en: "Ice Cream",           price: 48,  category: "Tatlılar",          description: "2 top, çikolata veya meyve sos",           description_en: "2 scoops, chocolate or fruit sauce",   image_url: null,                      tags: [],                 ingredients: ["icecream","chocolate","strawberry"],                        in_stock: true,  model_url: null },

  // ── ATIŞTIRRMALIKLAR ───────────────────────────────────────────────────────
  { id: "n1",  name: "Çıtır Tavuk",        name_en: "Crispy Chicken",      price: 95,  category: "Atıştırmalıklar",   description: "Crispy panko, ranch sos",                   description_en: "Crispy panko, ranch sauce",            image_url: null,                      tags: ["Popüler"],        ingredients: ["chicken","flour","egg","milk","hotsauce"],                  in_stock: true,  model_url: null },
  { id: "n2",  name: "Nachos",             name_en: "Nachos",              price: 85,  category: "Atıştırmalıklar",   description: "Çıtır mısır cipsi, kaşar, acı sos",        description_en: "Crispy corn chips, cheese, hot sauce", image_url: null,                      tags: ["Yeni"],           ingredients: ["corn","cheese","hotsauce","tomato"],                        in_stock: true,  model_url: null },
  { id: "n3",  name: "Patates Kızartması", name_en: "French Fries",        price: 65,  category: "Atıştırmalıklar",   description: "Çıtır, kekikli, ranch sos ile",            description_en: "Crispy, herbed, with ranch sauce",     image_url: null,                      tags: [],                 ingredients: ["flour","salt","oliveoil"],                                  in_stock: true,  model_url: null },
  { id: "n4",  name: "Peynirli Ekmek",     name_en: "Cheese Bread",        price: 55,  category: "Atıştırmalıklar",   description: "Fırından taze, kaşar ve cheddar",           description_en: "Fresh from oven, cheddar blend",       image_url: null,                      tags: [],                 ingredients: ["flour","cheese","butter","egg"],                            in_stock: true,  model_url: null },
  { id: "n5",  name: "Karışık Mezze",      name_en: "Mixed Mezze",         price: 110, category: "Atıştırmalıklar",   description: "Humus, patlıcan ezmesi, ezme, pide",        description_en: "Hummus, eggplant dip, ezme, pita",     image_url: null,                      tags: ["Şefin Seçimi"],   ingredients: ["eggplant","tomato","oliveoil","flour","garlic","lemon"],    in_stock: true,  model_url: null },
];

const CATS = ["Kahveler", "Sıcak İçecekler", "Soğuk İçecekler", "Kahvaltı", "Tostlar & Sandviçler", "Ana Yemekler", "Tatlılar", "Atıştırmalıklar"];

export default function DemoMenuPage() {
  return (
    <div data-demo-scroll style={{ position: "fixed", inset: 0, overflowY: "auto", overscrollBehavior: "none", touchAction: "pan-y", backgroundColor: "#fffbf7", color: "#1f2937" } as React.CSSProperties}>
      <DemoScrollFix />

      {/* Header */}
      <div className="sticky top-0 z-40 bg-white/80 backdrop-blur border-b border-gray-100 px-4 py-3 flex items-center gap-3">
        <Image src={LOGO} alt="Logo" width={32} height={32} className="w-8 h-8 rounded-lg object-cover" />
        <span className="font-bold text-gray-800 text-sm">Arôme Café & Bistro</span>
        <span className="ml-auto text-[10px] font-semibold px-2 py-0.5 rounded-full bg-green-100 text-green-600">Açık</span>
      </div>

      {/* Kapak */}
      <div className="relative w-full h-40 overflow-hidden">
        <Image src={COVER} alt="Kapak" fill className="object-cover" />
        <div className="absolute inset-0 bg-black/40" />
        <div className="absolute inset-0 flex flex-col items-center justify-center text-white">
          <p className="font-extrabold text-xl drop-shadow">Arôme Café & Bistro</p>
          <p className="text-xs text-white/80 mt-0.5">Kahve · Yemek · Tatlı</p>
        </div>
      </div>

      {/* Tabs */}
      <CategoryTabs categories={CATS} primaryColor={PRIMARY} bgColor="#fffbf7" />

      <div className="max-w-md mx-auto px-4 py-6">
        <MenuProductList
          products={PRODUCTS}
          orderedCats={CATS}
          primaryColor={PRIMARY}
          isEn={false}
          productLayout="list"
          imageRatio="square"
        />
      </div>

      <p className="text-center text-[10px] text-gray-300 pb-6">Bu bir demo menüdür · qefmenu.com</p>
    </div>
  );
}
